export default {
	'global-color-reference-blue001': 'rgb(var(--global-color-reference-blue001))',
	'global-color-reference-blue002': 'rgb(var(--global-color-reference-blue002))',
	'global-color-reference-blue003': 'rgb(var(--global-color-reference-blue003))',
	'global-color-reference-blue004': 'rgb(var(--global-color-reference-blue004))',
	'global-color-reference-purple001': 'rgb(var(--global-color-reference-purple001))',
	'global-color-reference-purple002': 'rgb(var(--global-color-reference-purple002))',
	'global-color-reference-white001': 'rgb(var(--global-color-reference-white001))',
	'global-color-reference-yellow001': 'rgb(var(--global-color-reference-yellow001))',
	'global-color-reference-red001': 'rgb(var(--global-color-reference-red001))',
	'global-color-reference-red002': 'rgb(var(--global-color-reference-red002))',
	'global-color-reference-black001': 'rgb(var(--global-color-reference-black001))',
	'global-color-reference-black002': 'rgb(var(--global-color-reference-black002))',
	'global-color-reference-orange001': 'rgb(var(--global-color-reference-orange001))',
	'global-color-reference-dark-grey001': 'rgb(var(--global-color-reference-dark-grey001))',
};
